### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by hyperknot** [Asupkay/Artblocks-Starter-Template#1]
It took me some time to realize what this loop does or doesn't do :-)

https://github.com/Asupkay/Artblocks-Starter-Template/blob/b06b2e4cde108200596a20b57219f9449fd98044/public/js/example.js#L5

**Comment by Asupkay** [comment]
Doesn't look like that loop does anything. Sorry that is a carry over from an old design. I'll delete it. Thanks for the issue :)

**Comment by Asupkay** [comment]
Fixed :)
